version: 0.2

#env:
#  variables:
#    key: "value"
#    key: "value"

phases:
  install:
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform  
      - terraform version
  build:
    commands:
      - echo "Post apply build"
  post_build:
    commands:
      - echo "Nothing to do in the post_build for now"

