version: 0.2

#env:
#  variables:
#    key: "value"
#    key: "value"

phases:
  install:
    commands:
      - sh entry-point.sh
  build:
    commands:
      - echo "Post apply build"
  post_build:
    commands:
      - echo "Nothing to do in the post_build for now"

