version: 0.2

#env:
#  variables:
#    key: "value"
#    key: "value"

phases:
  install:
    commands:
      - pip install boto3
      - wget https://releases.hashicorp.com/terraform/0.14.6/terraform_0.14.6_linux_amd64.zip
      - unzip terraform_0.14.6_linux_amd64.zip
      - mv terraform /usr/bin
      - rm terraform_0.14.6_linux_amd64.zip
      - terraform version
  build:
    commands:
      - echo "Post apply build"
  post_build:
    commands:
      - echo "Nothing to do in the post_build for now"

